name: city2graph_env
channels:
  - conda-forge/label/shapely_dev
  - conda-forge
  - pyg
  
dependencies:
  - python=3.12
  - shapely=2.1.0
  - geopandas
  - jupyter
  - overturemaps
  - momepy
  - pyg