[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "city2graph"
version = "0.1.0"
description = "A library that converts Overture Maps data into a graph representation using NetworkX"
authors = [
    {name = "Yuta Sato", email = "stein.stone.ishi@gmail.com"}
]
readme = "README.md"
license = {text = "BSD-3-Clause"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: GIS",
]
keywords = ["graph-neural-networks", "pytorch-geometric", "urban", "transportation", "mobility", "overturemaps", "gtfs"]
requires-python = ">=3.11,<4.0"
dependencies = [
    "networkx>=2.8",
    "shapely>=2.1.0",
    "geopandas>0.12.0",
    "libpysal>=4.12.1",
    "momepy",
    "overturemaps"
]

[project.optional-dependencies]
torch = [
    "torch>=2.4.0",
    "torch_geometric>=2.6.1",
    "pyg_lib",
    "torch_scatter",
    "torch_sparse",
    "torch_cluster",
    "torch_spline_conv"
]

[project.urls]
"Homepage" = "https://github.com/yu-ta-sato/city2graph"
"Documentation" = "https://ysato.blog/city2graph"
"Bug Tracker" = "https://github.com/yu-ta-sato/city2graph/issues"

[tool.poetry]
packages = [{include = "city2graph"}]

[tool.poetry.group.torch]
optional = true

[tool.poetry.group.torch.dependencies]
torch = ">=2.4.0"
torch-geometric = ">=2.6.1"

[tool.poetry.group.torch-cuda]
optional = true

[tool.poetry.group.torch-cuda.dependencies]
torch = {version = ">=2.4.0", extras = ["cuda"]}
torch-geometric = ">=2.6.1"
pyg_lib = "*"
torch_scatter = "*"
torch_sparse = "*"
torch_cluster = "*"
torch_spline_conv = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "*"
sphinx-autodoc-typehints = "*"
pydata-sphinx-theme = "*"
myst-parser = "*"
nbsphinx = "*"
numpydoc = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
ipython = "^8.14.0"
jupyter = "^1.0.0"
notebook = "^7.0.0"
black = "^23.3.0"
isort = "^5.12.0"