package:
  name: city2graph
  version: 0.1.0

source:
  path: ..
  
requirements:
  host:
    - python={{ environ.get('PYTHON_VERSION') }}
    - pip
    - setuptools
    - wheel
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - networkx
    - shapely
    - geopandas>=0.12.0
    - momepy
    - overturemaps
    - {{ environ.get('CONDA_PYG_CONSTRAINT') }}

build:
  number: 0
  script: {{ environ.get('PYTHON') }} -m pip install . -vv
  string: py{{ environ.get('PYTHON_VERSION', '').replace('.', '') }}_pyg_{{ environ.get('PYG_VERSION').replace('.', '') }}_{{ environ.get('CUDA_VERSION') }}
  skip: true  # [py<310]