name: Build and Deploy Python Package

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Build wheel
        run: uv build --wheel --out-dir dist

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: uv publish dist/*.whl