name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "uv.lock"

      - name: Sync dependencies
        run: |
          uv sync --locked --all-extras --dev
      - name: Run tests with coverage
        run: |
          uv run pytest --cov=city2graph --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Set CODECOV_TOKEN in repository secrets
          files: coverage.xml
          fail_ci_if_error: true
